build:
    image: default-bionic
    environment:
        php: 8.1.2
        ini:
            xdebug.mode: coverage
    nodes:
    analysis:
        tests:
            override:
                - php-scrutinizer-run

    phpunit:
        dependencies:
            override:
                - composer self-update
                - composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

        tests:
            override:
                - command: ./vendor/bin/phpunit --coverage-clover ./coverage.xml
                  on_node: 1
                  coverage:
                      file: coverage.xml
                      format: php-clover