<?php
namespace Apie\Tests\IntegrationTests\Webdav;

use Apie\Core\BoundedContext\BoundedContextId;
use Apie\IntegrationTests\IntegrationTestHelper;
use Apie\IntegrationTests\Interfaces\TestApplicationInterface;
use Apie\IntegrationTests\Requests\ListFilesWebdavCall;
use Apie\IntegrationTests\Requests\WebdavTestRequestInterface;
use Apie\IntegrationTests\WebdavTestHelper;
use Apie\PhpunitMatrixDataProvider\MakeDataProviderMatrix;
use Generator;
use PHPUnit\Framework\TestCase;
use ReflectionMethod;

class ControllerTest extends TestCase
{
    use MakeDataProviderMatrix;

    private function shouldOverwriteFixtures(): bool
    {
        return true;
    }

    public static function it_can_display_test_page_provider(): Generator
    {
        yield from self::createDataProviderFrom(
            new ReflectionMethod(__CLASS__, 'it_can_display_test_page'),
            new IntegrationTestHelper()
        );
    }

    #[\PHPUnit\Framework\Attributes\DataProvider('it_can_display_test_page_provider')]
    #[\PHPUnit\Framework\Attributes\RunInSeparateProcess]
    #[\PHPUnit\Framework\Attributes\Test]
    public function it_can_display_test_page(TestApplicationInterface $testApplication)
    {
        $testApplication->bootApplication();
        $response = $testApplication->httpRequestGet('/webdav');
        $this->assertEquals(200, $response->getStatusCode(), 'Body is ' . $response->getBody());
        $this->assertStringContainsString('<footer>Generated by SabreDAV', $response->getBody());
        $this->assertEquals('text/html; charset=utf-8', $response->getHeaderLine('Content-Type'));
        $testApplication->cleanApplication();
    }

    public static function it_can_retrieve_folder_listings_provider(): Generator
    {
        yield from self::createDataProviderFrom(
            new ReflectionMethod(__CLASS__, 'it_can_retrieve_folder_listings'),
            new WebdavTestHelper()
        );
    }

    #[\PHPUnit\Framework\Attributes\DataProvider('it_can_retrieve_folder_listings_provider')]
    #[\PHPUnit\Framework\Attributes\RunInSeparateProcess]
    #[\PHPUnit\Framework\Attributes\Test]
    public function it_can_retrieve_folder_listings(
        TestApplicationInterface $testApplication,
        WebdavTestRequestInterface $request
    ) {
        $testApplication->bootApplication();
        $response = $testApplication->httpRequest($request);
        $this->assertEquals($request->getExpectedStatusCode(), $response->getStatusCode(), 'Body is ' . substr($response->getBody(), 0, 100));
        $fixtureFile = __DIR__ . '/../../fixtures/Webdav/ControllerTest_it_can_retrieve_folder_listings_' . $request->getTestName() . '.xml';
        if ($this->shouldOverwriteFixtures() || !file_exists($fixtureFile)) {
            $xmlString = $response->getBody();
            $dom = new \DOMDocument();
            $dom->preserveWhiteSpace = false;
            $dom->formatOutput = true;
            $dom->loadXML($xmlString);
            file_put_contents($fixtureFile, $dom->saveXML());
        }
        $this->assertXmlStringEqualsXmlFile($fixtureFile, $response->getBody());
        $this->assertEquals('application/xml; charset=utf-8', $response->getHeaderLine('Content-Type'));
        $testApplication->cleanApplication();
    }

    public static function it_returns_404_on_missing_asset_provider(): Generator
    {
        yield from self::createDataProviderFrom(
            new ReflectionMethod(__CLASS__, 'it_returns_404_on_missing_asset'),
            new IntegrationTestHelper()
        );
    }

    #[\PHPUnit\Framework\Attributes\DataProvider('it_returns_404_on_missing_asset_provider')]
    #[\PHPUnit\Framework\Attributes\RunInSeparateProcess]
    #[\PHPUnit\Framework\Attributes\Test]
    public function it_returns_404_on_missing_asset(TestApplicationInterface $testApplication)
    {
        $testApplication->bootApplication();
        $response = $testApplication->httpRequestGet('/webdav/missing');
        $this->assertEquals(404, $response->getStatusCode(), 'Body is ' . $response->getBody());
        $testApplication->cleanApplication();
    }
}
