<?php
namespace Apie\Tests\IntegrationTests\Webdav;

use Apie\Faker\Datalayers\FakerDatalayer;
use Apie\IntegrationTests\Applications\Laravel\LaravelTestApplication;
use Apie\IntegrationTests\IntegrationTestHelper;
use Apie\IntegrationTests\Interfaces\TestApplicationInterface;
use Apie\IntegrationTests\Requests\BootstrapRequestInterface;
use Apie\IntegrationTests\Requests\ListFilesWebdavCall;
use Apie\IntegrationTests\Requests\WebdavTestRequestInterface;
use Apie\IntegrationTests\WebdavTestHelper;
use Apie\PhpunitMatrixDataProvider\MakeDataProviderMatrix;
use Generator;
use PHPUnit\Framework\TestCase;
use ReflectionMethod;

class ControllerTest extends TestCase
{
    use MakeDataProviderMatrix;

    private function shouldOverwriteFixtures(): bool
    {
        return true;
    }

    public static function it_can_display_test_page_provider(): Generator
    {
        yield from self::createDataProviderFrom(
            new ReflectionMethod(__CLASS__, 'it_can_display_test_page'),
            new IntegrationTestHelper()
        );
    }

    #[\PHPUnit\Framework\Attributes\DataProvider('it_can_display_test_page_provider')]
    #[\PHPUnit\Framework\Attributes\RunInSeparateProcess]
    #[\PHPUnit\Framework\Attributes\Test]
    public function it_can_display_test_page(TestApplicationInterface $testApplication)
    {
        $testApplication->bootApplication();
        $response = $testApplication->httpRequestGet('/webdav');
        $this->assertEquals(200, $response->getStatusCode(), 'Body is ' . $response->getBody());
        $this->assertStringContainsString('<footer>Generated by SabreDAV', $response->getBody());
        $this->assertEquals('text/html; charset=utf-8', $response->getHeaderLine('Content-Type'));
        $testApplication->cleanApplication();
    }

    public static function it_can_retrieve_folder_listings_provider(): Generator
    {
        yield from self::createDataProviderFrom(
            new ReflectionMethod(__CLASS__, 'it_can_retrieve_folder_listings'),
            new WebdavTestHelper()
        );
    }

    #[\PHPUnit\Framework\Attributes\DataProvider('it_can_retrieve_folder_listings_provider')]
    #[\PHPUnit\Framework\Attributes\RunInSeparateProcess]
    #[\PHPUnit\Framework\Attributes\Test]
    public function it_can_retrieve_folder_listings(
        TestApplicationInterface $testApplication,
        WebdavTestRequestInterface $request
    ) {
        if ($testApplication instanceof LaravelTestApplication && $request instanceof ListFilesWebdavCall) {
            // Laravel's filesystem integration test setup is broken for webdav
            $this->markTestSkipped('Laravel filesystem integration test setup is broken for webdav');
        }
        $testApplication->bootApplication();
        if ($request instanceof BootstrapRequestInterface) {
            $request->bootstrap($testApplication);
        }
        $response = $testApplication->httpRequest($request);
        $body = $response->getBody();
        // remove <s:stacktrace> because it is not deterministic because of full file path
        $body = preg_replace('/<s:stacktrace>.*?<\/s:stacktrace>/s', '', (string) $body);
        // remove <s:file> because they are not deterministic because of full file path
        $body = preg_replace('/<s:file>.*?<\/s:file>/s', '', (string) $body);
        if ($testApplication->getApplicationConfig()->getDatalayerImplementation()->name !== FakerDatalayer::class) {
            $this->assertEquals($request->getExpectedStatusCode(), $response->getStatusCode(), 'Body is ' . substr($response->getBody(), 0, 400));
            $fixtureFile = __DIR__ . '/../../fixtures/Webdav/ControllerTest_it_can_retrieve_folder_listings_' . $request->getTestName() . '.xml';
        
            if ($this->shouldOverwriteFixtures() || !file_exists($fixtureFile)) {
                $xmlString = $body;
                $dom = new \DOMDocument();
                $dom->preserveWhiteSpace = false;
                $dom->formatOutput = true;
                $dom->loadXML($xmlString);
                file_put_contents($fixtureFile, $dom->saveXML());
            }
            $this->assertXmlStringEqualsXmlFile($fixtureFile, $body);
        }
        $this->assertEquals('application/xml; charset=utf-8', $response->getHeaderLine('Content-Type'));
        $testApplication->cleanApplication();
    }

    public static function it_returns_404_on_missing_asset_provider(): Generator
    {
        yield from self::createDataProviderFrom(
            new ReflectionMethod(__CLASS__, 'it_returns_404_on_missing_asset'),
            new IntegrationTestHelper()
        );
    }

    #[\PHPUnit\Framework\Attributes\DataProvider('it_returns_404_on_missing_asset_provider')]
    #[\PHPUnit\Framework\Attributes\RunInSeparateProcess]
    #[\PHPUnit\Framework\Attributes\Test]
    public function it_returns_404_on_missing_asset(TestApplicationInterface $testApplication)
    {
        $testApplication->bootApplication();
        $response = $testApplication->httpRequestGet('/webdav/missing');
        $this->assertEquals(404, $response->getStatusCode(), 'Body is ' . $response->getBody());
        $testApplication->cleanApplication();
    }
}
