/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { NestedRecord, Primitive, SubmitField } from "apie-form-elements/dist/types/components";
export { NestedRecord, Primitive, SubmitField } from "apie-form-elements/dist/types/components";
export namespace Components {
    interface ApieSkeletonForm {
        "initialValue"?: NestedRecord<SubmitField>;
        "internalState": NestedRecord<Primitive>;
        "polymorphicFormDefinition"?: Record<string, string>;
        "validationErrors": NestedRecord<string>;
        "value": NestedRecord<SubmitField>;
    }
}
declare global {
    interface HTMLApieSkeletonFormElement extends Components.ApieSkeletonForm, HTMLStencilElement {
    }
    var HTMLApieSkeletonFormElement: {
        prototype: HTMLApieSkeletonFormElement;
        new (): HTMLApieSkeletonFormElement;
    };
    interface HTMLElementTagNameMap {
        "apie-skeleton-form": HTMLApieSkeletonFormElement;
    }
}
declare namespace LocalJSX {
    interface ApieSkeletonForm {
        "initialValue"?: NestedRecord<SubmitField>;
        "internalState"?: NestedRecord<Primitive>;
        "polymorphicFormDefinition"?: Record<string, string>;
        "validationErrors"?: NestedRecord<string>;
        "value"?: NestedRecord<SubmitField>;
    }
    interface IntrinsicElements {
        "apie-skeleton-form": ApieSkeletonForm;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "apie-skeleton-form": LocalJSX.ApieSkeletonForm & JSXBase.HTMLAttributes<HTMLApieSkeletonFormElement>;
        }
    }
}
