FROM debian:trixie

RUN apt-get update && apt-get install -y \
    autoconf \
    build-essential \
    bison \
    pkg-config \
    re2c \
    libxml2-dev \
    libsqlite3-dev \
    libcurl4-openssl-dev \
    libonig-dev \
    libzip-dev \
    git \
 && git clone --depth=1 https://github.com/php/php-src.git /usr/src/php \
 && cd /usr/src/php \
 && ./buildconf \
 && ./configure --enable-mbstring --with-openssl \
 && make -j"$(nproc)" \
 && make install

CMD ["php", "-v"]