services:
  Apie\Common\ApieFacade:
    arguments:
      - '@apie.route_definitions.provider'
      - '@Apie\Core\BoundedContext\BoundedContextHashmap'
      - '@Apie\Serializer\Serializer'
      - '@Apie\Core\Repositories\ApieRepository'
  
  apie:
    alias: Apie\Common\ApieFacade
    public: true