services:
  apie.route_definitions.provider:
    class: Apie\Core\RouteDefinitions\ChainedRouteDefinitionProvider
    factory: ['Apie\ApieBundle\Wrappers\GeneralServiceFactory', 'createRoutedDefinitionProvider']
    arguments:
      - !tagged apie.core.route_definition

  Apie\Core\BoundedContext\BoundedContextHashmap:
    factory: ["@apie.bounded_context.hashmap_factory", "create"]

  apie.bounded_context.hashmap:
    alias: Apie\Core\BoundedContext\BoundedContextHashmap
    public: true

  apie.context.factory:
    alias: Apie\Core\ContextBuilders\ContextBuilderFactory
    public: true

  Apie\Core\Datalayers\ApieDatalayer:
    alias: Apie\ApieBundle\Wrappers\RequestAwareInMemoryDatalayer