services:
  Apie\HtmlBuilders\Factories\ComponentFactory:
    arguments:
      - '@Apie\HtmlBuilders\Configuration\ApplicationConfiguration'
      - '@Apie\Core\BoundedContext\BoundedContextHashmap'
      - '@Apie\HtmlBuilders\Factories\FormComponentFactory'

  Apie\HtmlBuilders\Factories\FormComponentFactory:
    factory: ['Apie\HtmlBuilders\Factories\FormComponentFactory', 'create']

  Apie\HtmlBuilders\Configuration\ApplicationConfiguration:
    arguments:
      -
        base_url: '%apie.cms.base_url%'
