services:
  # https://github.com/symfony/psr-http-message-bridge/issues/106
  Symfony\Bridge\PsrHttpMessage\ArgumentValueResolver\PsrServerRequestResolver:
    arguments: ['@Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory']
    tags:
      - { name: controller.argument_value_resolver, priority: 50 }

  Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory:
    arguments: ['@Nyholm\Psr7\Factory\Psr17Factory', '@Nyholm\Psr7\Factory\Psr17Factory', '@Nyholm\Psr7\Factory\Psr17Factory', '@Nyholm\Psr7\Factory\Psr17Factory']

  Nyholm\Psr7\Factory\Psr17Factory:

  Symfony\Bridge\PsrHttpMessage\EventListener\PsrResponseListener:
    tags: ['kernel.event_subscriber']