services:

  Apie\RestApi\RouteDefinitions\RestApiRouteDefinitionProvider:
    tags: 
      - name: apie.core.route_definition

  Apie\RestApi\OpenApi\OpenApiGenerator:
    arguments:
      - '@Apie\Core\ContextBuilders\ContextBuilderFactory'
      - '@Apie\SchemaGenerator\ComponentsBuilderFactory'
      - '@apie.route_definitions.provider'
      - '@Apie\Serializer\Serializer'
      - '%apie.rest_api.base_url%'

  Apie\RestApi\Controllers\OpenApiDocumentationController:
    arguments:
      - '@Apie\Core\BoundedContext\BoundedContextHashmap'
      - '@Apie\RestApi\OpenApi\OpenApiGenerator'
    tags: ['controller.service_arguments']
  
  Apie\RestApi\Controllers\CreateResourceController:
    arguments:
      - '@Apie\Core\ContextBuilders\ContextBuilderFactory'
      - '@Apie\Core\BoundedContext\BoundedContextHashmap'
      - '@Apie\RestApi\Actions\CreateObjectAction'
      - '@Apie\Serializer\EncoderHashmap'
      - '@Apie\Serializer\DecoderHashmap'
    tags: ['controller.service_arguments']

  Apie\RestApi\Controllers\RunGlobalMethodController:
    arguments:
      - '@Apie\Core\ContextBuilders\ContextBuilderFactory'
      - '@Apie\Core\BoundedContext\BoundedContextHashmap'
      - '@Apie\RestApi\Actions\RunAction'
      - '@Apie\Serializer\EncoderHashmap'
      - '@Apie\Serializer\DecoderHashmap'
    tags: ['controller.service_arguments']

  Apie\RestApi\Actions\CreateObjectAction:
    arguments:
      - '@Apie\Serializer\Serializer'

  Apie\RestApi\Actions\RunAction:
    arguments:
      - '@Apie\Serializer\Serializer'
