# Apie core services
services:

  Apie\ApieBundle\Routing\ApieRouteLoader:
    arguments:
      - "@apie.route_definitions.provider"
      - "@apie.bounded_context.hashmap"
      - '@Apie\Common\RouteDefinitions\PossibleRoutePrefixProvider'
      - '@Apie\Core\ContextBuilders\ContextBuilderFactory'
      - "%apie.scan_bounded_contexts%"
    tags: [routing.loader]

  Apie\ApieBundle\ContextBuilders\SessionContextBuilder:
    arguments:
      - '@request_stack'
    tags: [apie.core.context_builder]

  Apie\ApieBundle\ContextBuilders\CsrfTokenContextBuilder:
    arguments:
      - '@?Symfony\Component\Security\Csrf\CsrfTokenManagerInterface'
    tags: [apie.core.context_builder]

  Apie\Common\Interfaces\BoundedContextSelection:
    alias: Apie\ApieBundle\Wrappers\BoundedContextSelected

  Apie\ApieBundle\Wrappers\BoundedContextSelected:
    arguments:
      - '@request_stack'
      - '@Apie\Core\BoundedContext\BoundedContextHashmap'
    tags: ['apie.context']

  Apie\Common\Interfaces\DashboardContentFactoryInterface:
    alias: Apie\ApieBundle\Wrappers\DashboardContentFactory

  Apie\ApieBundle\Wrappers\DashboardContentFactory:
    arguments:
      - '@?twig'

  Apie\ApieBundle\EventListeners\SendKernelExceptionOnCaughtExceptionListener:
    arguments:
      - '@Symfony\Component\HttpKernel\HttpKernelInterface'
      - '@request_stack'
      - '@?profiler_listener'
    tags: ['kernel.event_subscriber']

  Apie\ApieBundle\EventListeners\RenderErrorListener:
    arguments:
      - '@?Apie\HtmlBuilders\ErrorHandler\CmsErrorRenderer'
      - '@Apie\Common\ErrorHandler\ApiErrorRenderer'
      - '@Psr\Log\LoggerInterface'
      - '%apie.cms.base_url%'
    tags: ['kernel.event_subscriber']
