# Apie core services
services:
  apie.bounded_context.hashmap_factory:
      class: Apie\ApieBundle\Wrappers\BoundedContextHashmapFactory
      arguments:
        - "%apie.bounded_contexts%"

  Apie\Core\ContextBuilders\ContextBuilderFactory:
    factory: ['Apie\ApieBundle\Wrappers\GeneralServiceFactory', 'createContextBuilderFactory']
    arguments:
      - !tagged apie.core.context_builder

  Apie\ApieBundle\Routing\ApieRouteLoader:
    arguments:
      - "@apie.route_definitions.provider"
      - "@apie.bounded_context.hashmap"
    tags: [routing.loader]

  Apie\ApieBundle\ContextBuilders\ServiceContextBuilder:
    arguments:
      - !tagged_locator { tag: 'apie.context' }
    tags: [apie.core.context_builder]

  Apie\ApieBundle\Wrappers\RequestAwareInMemoryDatalayer:
    arguments:
      - '@Apie\ApieBundle\Wrappers\BoundedContextSelected'

  Apie\ApieBundle\Wrappers\BoundedContextSelected:
    arguments:
      - '@request_stack'
      - '@Apie\Core\BoundedContext\BoundedContextHashmap'
    tags: ['apie.context']