services:
  Apie\HtmlBuilders\Interfaces\ComponentRendererInterface:
    factory:
      - 'Apie\ApieBundle\Wrappers\CmsRendererFactory'
      - createRenderer
    arguments:
      - '@Apie\HtmlBuilders\Assets\AssetManager'