version: "3"
volumes:
  volume_database_project:

services:
  mysql:
    image: mysql:8.0
    container_name: apie_playground_mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: project
      MYSQL_USER: project
      MYSQL_PASSWORD: project
    volumes:
      - volume_database_project:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: apie_playground_phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "81:80"

  web:
    build:
      context: ../
      dockerfile: ./playground/.docker/Dockerfile
    container_name: apie_playground_web
    volumes:
      - ./app/ApiePlayground:/var/www/html/src/ApiePlayground
      - ../packages:/packages
      - ./.docker/virtualhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./.docker/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    ports:
      - "82:80"
    labels:
      traefik.enable: true
      traefik.http.routers.lesapp-api-nginx.priority: 1
      traefik.http.routers.lesapp-api-nginx.rule: HostRegexp(`apie-playground.localtest.me`)
      traefik.http.routers.lesapp-api-nginx.entrypoints: "web"
      traefik.http.routers.lesapp-api-nginx.tls: tfalse
    environment:
      - APIE_STARTER_SETUP=maximum
      - APIE_STARTER_ENABLE_CMS=1
      - APIE_STARTER_FRAMEWORK=Symfony
      - APIE_STARTER_ENABLE_USER=0
      - DATABASE_URL=mysql://project:project@mysql:3306/project
    depends_on:
      - mysql

  mailhog:
    image: mailhog/mailhog
    container_name: apie_playground_mailhog
    ports:
      - "1025:1025" # smtp server
      - "8025:8025" # web ui
