name: PHPUnit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        coverage: pcov
        ini-values: pcov.directory=packages

    - uses: actions/checkout@v2

    - name: Validate composer.json
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.json') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run test suite
      run: vendor/bin/simple-phpunit --coverage-clover=coverage.xml --coverage-html=coverage
      
    - uses: actions/upload-artifact@v3
      with:
        name: Code coverage (HTML)
        path: coverage

    - uses: actions/upload-artifact@v3
      with:
        name: Code coverage (Clover xml)
        path: coverage.xml