name: PHPUnit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        coverage: pcov
        ini-values: pcov.directory=packages

    - uses: actions/checkout@v2

    - name: Validate composer.json
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.json') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run test suite
      run: vendor/bin/simple-phpunit --coverage-clover=clover.xml --coverage-html=coverage
      
    - name: phpunit-coverage-badge
      uses: timkrase/phpunit-coverage-badge@v1.2.0
      with:
        coverage_badge_path: coverage/coverage_badge.svg

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
      with:
        source_file: 'coverage'
        destination_repo: 'apie-lib/apie-lib.github.io'
        destination_folder: '.'
        user_email: 'pieter_jordaan@Hotmail.com'
        user_name: 'pjordaan'
        commit_message: 'Update code coverage'

    - uses: actions/upload-artifact@v3
      with:
        name: Code coverage (HTML)
        path: coverage

    - uses: actions/upload-artifact@v3
      with:
        name: Code coverage (Clover xml)
        path: clover.xml

    - name: Run static code analysis
      run: vendor/bin/phpstan