name: Split Monorepo

env:
    PAT: ${{ secrets.ACCESS_TOKEN }}

on:
  push:
    branches:
      - main
      - 1.0.0

    tags:
      - '*'

jobs:
  provide_packages_json:
    runs-on: ubuntu-latest

    steps:
      -
        uses: actions/checkout@v2

      -   uses: shivammathur/setup-php@v2
          with:
            php-version: 8.1
            coverage: none

      -   uses: "ramsey/composer-install@v1"

      -
        id: output_data
        run: echo "::set-output name=matrix::$(vendor/bin/monorepo-builder packages-json)"

    outputs:
      matrix: ${{ steps.output_data.outputs.matrix }}

  split_monorepo:
    needs: provide_packages_json

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ${{fromJson(needs.provide_packages_json.outputs.matrix)}}

    steps:
      -
        uses: actions/checkout@v2

      # no tag
      - name: Pushes to apie-lib/${{ matrix.package }}, branch '${{ github.ref_name }}'
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
        with:
          source_file: 'packages/${{ matrix.package }}'
          destination_repo: 'apie-lib/${{ matrix.package }}'
          destination_branch: '${{ github.ref_name }}'
          user_email: 'pieter_jordaan@hotmail.com'
          user_name: 'pjordaan'

      # with tag
      -
        name: Pushes tag to apie-lib/${{ matrix.package }}
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: "symplify/monorepo-split-github-action@2.1"
        with:
          tag: ${GITHUB_REF#refs/tags/}
          package_directory: 'packages/${{ matrix.package }}'
          repository_organization: 'apie-lib'
          repository_name: '${{ matrix.package }}'
          user_name: "Pieter Jordaan"
          user_email: "pieter_jordaan@hotmail.com"

