name: Split Monorepo

env:
    PAT: ${{ secrets.ACCESS_TOKEN }}

on:
  push:
    branches:
      - main

    tags:
      - '*'

jobs:
  provide_packages_json:
    runs-on: ubuntu-latest

    steps:
      -
        uses: actions/checkout@v2

      -   uses: shivammathur/setup-php@v2
          with:
            php-version: 8.1
            coverage: none

      -   uses: "ramsey/composer-install@v1"

      -
        id: output_data
        run: echo "::set-output name=matrix::$(vendor/bin/monorepo-builder packages-json)"

    outputs:
      matrix: ${{ steps.output_data.outputs.matrix }}

  split_monorepo:
    needs: provide_packages_json

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ${{fromJson(needs.provide_packages_json.outputs.matrix)}}

    steps:
      -
        uses: actions/checkout@v2

      # no tag
      -
        name: Monorepo Split of ${{ matrix.package }} (no tag)
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: "symplify/monorepo-split-github-action@2.1"
        with:
          package_directory: 'packages/${{ matrix.package }}'
          repository_organization: 'apie-lib'
          repository_name: '${{ matrix.package }}'
          user_name: "Pieter Jordaan"
          user_email: "pieter_jordaan@hotmail.com"
          branch: '${{ github.ref_name }}'

      # with tag
      -
        name: Monorepo Split of ${{ matrix.package }} (tag)
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: "symplify/monorepo-split-github-action@2.1"
        with:
          tag: ${GITHUB_REF#refs/tags/}
          package_directory: 'packages/${{ matrix.package }}'
          repository_organization: 'apie-lib'
          repository_name: '${{ matrix.package }}'
          user_name: "Pieter Jordaan"
          user_email: "pieter_jordaan@hotmail.com"

